apps/flight/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('select_destination/<str:param>', views.select_destination,
     name="select_destination"),
    path('search_offers/', views.search_offers, name="search_offers"),
    path('price_offers/', views.price_offer, name="price_offer"),
    path('blog/', views.PostList.as_view(), name='home'),
    path('blog/<slug:slug>/', views.PostDetail.as_view(), name='post_detail')


   
]

fintechengine/urls.py
from django.contrib import admin
from django.urls import include, path
from rest_framework import routers
from apps.api_app import views
from apps.payments.views import HomePageView

# from ninja import NinjaAPI
# from apps.roicalculations.api import api as sample_api

from django.conf.urls.static import static
from django.conf import settings

from django.views import generic
from rest_framework.schemas import get_schema_view
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView
)
from rest_framework import views, serializers, status
from rest_framework.response import Response

# class MessageSerializer(serializers.Serializer):
#     message = serializers.CharField()
# class EchoView(views.APIView):
#     def post(self, request, *args, **kwargs):
#         serializer = MessageSerializer(data=request.data)
#         serializer.is_valid(raise_exception=True)
#         return Response(
#             serializer.data, status=status.HTTP_201_CREATED)
        
# router = routers.DefaultRouter()
# router.register(r'users', views.UserViewSet)
# router.register(r'groups', views.GroupViewSet)
# router.register(r'api_app', views.GroupViewSet)
# router.register(r'snippets', views.GroupViewSet)


# api = NinjaAPI(title="ROI investment Rest API Docs", docs_url="/docs")
# api.add_router("", sample_api)


urlpatterns = [
    path('admin/', admin.site.urls),
    # path('router/', include(router.urls)),
    path('snippets/', include('apps.snippets.urls')),
    path('', include('apps.flight.urls')),
    # path('api/v1/flight/', include('apps.flight.urls')),
    # path("api/", api.urls), # Ninja with data api
    path('payments/', include('apps.payments.urls')),
    path('stripe-store/', HomePageView.as_view(), name='home'),
    path('api-app/', include('apps.api_app.urls')),
    # path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    # path("", include("apps.authentication.urls")),
    # path("", include("apps.home.urls"))
]
#
# if settings.DEBUG:  # new
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# authentification system
#
# urlpatterns = [
#     path(r'^$', generic.RedirectView.as_view(
#          url='/api/', permanent=False)),
#     path(r'^api/$', get_schema_view()),
#     path(r'^api/auth/', include(
#         'rest_framework.urls', namespace='rest_framework')),
#     path(r'^api/auth/token/obtain/$', TokenObtainPairView.as_view()),
#     path(r'^api/auth/token/refresh/$', TokenRefreshView.as_view()),
# ]

apps/flight/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
STATUS = (
    (0,"Draft"),
    (1,"Publish")
)

class Post(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(User, on_delete= models.CASCADE,related_name='blog_posts')
    updated_on = models.DateTimeField(auto_now= True)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title
    
    

apps/flight/views.py
from ast import keyword
from distutils.log import error
from urllib import response
from django.shortcuts import render
from django.views import generic
from django.views.decorators.csrf import csrf_protect
from django.http import HttpResponse, Http404
from django.template import loader
from amadeus import Client, ResponseError, Location
from django.http import JsonResponse
from .models import Post
from apps import flight
# user Interface consuming the API within the Django Framework

def index(request):
    context = {'username': 'joelwembo'}
    return render(request, 'flight/index.html', context)


amadeus = Client(client_id='3HcWAkvN1fp6wxe3o5fXWAiMGedUzCxV', client_secret='2N4SnYPn4gDt9BP3')

def select_destination(req, param):
    if req.method == "GET":
        try:
            print(param)
            response = amadeus.reference_data.locations.get(keyword=param, subType=Location.ANY)
            context = {
                "data" : response.data
            }
            return JsonResponse(context)
        except ResponseError as error:
            print(error)
    else:
        return JsonResponse({"error": "Invalid request method"})   
    
    
def search_offers(req):
    if req.method == "GET":
        try:
            origin_code = req.GET["originCode"]
            destination_code = req.GET["destinationCode"]
            departure_date = req.GET["departureDate"]
            response = amadeus.shopping.flight_offers.search.get(  
                  originLocationCode=origin_code, 
                  destinationLocationCode=destination_code,
                  departureDate=departure_date, adults=2                                              
                                                                  
                        )
            
            context = {
                "data" : response.data
            }
            return JsonResponse(context)
        except ResponseError as error:
            print (error)
            
    else:
        return JsonResponse({"error": "Invalid request method"})        
                
    
    
    
def price_offer(req):
    if req.method == "GET":
        try:
            flight = req.POST['flight']
            response = amadeus.shopping.flight_offers.pricing.post(flight)
            print(response.data)
            return JsonResponse(response.data)
  
        except ResponseError as error:
            print(error)
            
    else:
        return JsonResponse({"error": "Invalid request method"})  
    
def book_flight(req):
    if req.method == "POST":
        try:
            flight = req.POST['flight']
            traveler = req.POST['traveler']
            booking = amadeus.booking.flight_orders.post(flight, traveler)
            return JsonResponse(booking)
        except ResponseError as error:
            print(error)
            
    else:
        return JsonResponse({"error": "Invalid request method"})        
        
       
class PostList(generic.ListView):
    queryset = Post.objects.filter(status=1).order_by('-created_on')
    template_name = 'flight/blog.html'

class PostDetail(generic.DetailView):
    model = Post
    template_name = 'flight/post_detail.html'

apps/templates/flight/base.html
{% block sidebar %}

<style>
        .card{
            box-shadow: 0 16px 48px #E3E7EB;
        }

</style>

<!-- Sidebar Widgets Column -->
<div class="col-md-4 float-right ">
<div class="card my-4">
        <h5 class="card-header">About Us</h5>
    <div class="card-body">
        <p class="card-text"> This awesome blog is made on the top of our Favourite full stack Framework 'Django', follow up the tutorial to learn how we made it..!</p>
        <a href="https://djangocentral.com/building-a-blog-application-with-django"
           class="btn btn-danger">Know more!!</a>
    </div>
</div>
</div>

{% endblock sidebar %}

apps/templates/flight/blog.html
<html>
    <html lang="en">
        <head>
          <!-- Required meta tags -->
          <meta charset="utf-8">
          <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      
          <!-- Bootstrap CSS -->
          <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
      
          <title>Blog Flights | Amadeux </title>
        </head>
<style>
    .card{
        box-shadow: 0 16px 48px #E3E7EB;
    }

</style>

<!-- Sidebar Widgets Column -->
<div class="col-md-4 float-right ">
<div class="card my-4">
    <h5 class="card-header">About Us</h5>
<div class="card-body">
    <p class="card-text"> This awesome blog is made on the top of our Favourite full stack Framework 'Django', follow up the tutorial to learn how we made it..!</p>
    <a href="https://djangocentral.com/building-a-blog-application-with-django"
       class="btn btn-danger">Know more!!</a>
</div>
</div>
</div>
{% block content %}
<style>
    body {
        font-family: "Roboto", sans-serif;
        font-size: 18px;
        background-color: #fdfdfd;
    }

    .head_text {
        color: white;
    }

    .card {
        box-shadow: 0 16px 48px #E3E7EB;
    }
</style>

<header class="masthead">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class=" col-md-8 col-md-10 mx-auto">
                <div class="site-heading">
                    <h3 class=" site-heading my-4 mt-3 text-white"> Welcome to my awesome Blog </h3>
                    <p class="text-light">We Love Django As much as you do..! &nbsp
                    </p>
                </div>
            </div>
        </div>
    </div>
</header>
<div class="container">
    <div class="row">
        <!-- Blog Entries Column -->
        <div class="col-md-8 mt-3 left">
            {% for post in post_list %}
            <div class="card mb-4">
                <div class="card-body">
                    <h2 class="card-title">{{ post.title }}</h2>
                    <p class="card-text text-muted h6">{{ post.author }} | {{ post.created_on}} </p>
                    <p class="card-text">{{post.content|slice:":200" }}</p>
                    <a href="{% url 'post_detail' post.slug  %}" class="btn btn-primary">Read More &rarr;</a>
                </div>
            </div>
            {% endfor %}
        </div>
        <style>
            .card{
                box-shadow: 0 16px 48px #E3E7EB;
            }
           
    </style>
    
    <!-- Sidebar Widgets Column -->
    <div class="col-md-4 float-right ">
    <div class="card my-4">
            <h5 class="card-header">About Us</h5>
        <div class="card-body">
            <p class="card-text"> This awesome blog is made on the top of our Favourite full stack Framework 'Django', follow up the tutorial to learn how we made it..!</p>
            <a href="#"
               class="btn btn-danger">Know more!</a>
        </div>
    </div>
    </div>
    </div>
</div>
{%endblock%}

</html>

apps/templates/flight/index.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Flights | Amadeux </title>
  </head>
  <body>
   
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark border-dark">
      <div class="container">
        <a href="/" class="navbar-brand">Flights</a>
        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <div class="navbar-nav">
            <a href="/" class="nav-item nav-link">Home</a>
          </div>
          <div class="navbar-nav">
            <a href="/" class="nav-item nav-link">About</a>
          </div>
          <div class="navbar-nav">
            <a href="/" class="nav-item nav-link">Contact</a>
          </div>
        </div>
      </div>
    </nav>
    {% block content %}
    <div class="container">
      <h1>Flights | Amadeux</h1>

      <h3>Enjoy your Search</h3>
  
      <p>
        <h1>Hello {{ context }}</h1>
      </p>
    </div>

    {% endblock %}

    

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

apps/templates/flight/post_detail.html
<html lang="en">
    <head>
      <!-- Required meta tags -->
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  
      <!-- Bootstrap CSS -->
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  
      <title>Blog Details Flights | Amadeux </title>
    </head>

<style>
    .card{
        box-shadow: 0 16px 48px #E3E7EB;
    }

</style>

<body>
<!-- Sidebar Widgets Column -->
{% block content %}
<div class="col-md-4 float-right ">
<div class="card my-4">
    <h5 class="card-header">About Us</h5>
<div class="card-body">
    <p class="card-text"> This awesome blog is made on the top of our Favourite full stack Framework 'Django', follow up the tutorial to learn how we made it..!</p>
    <a href="https://djangocentral.com/building-a-blog-application-with-django"
       class="btn btn-danger">Know more!!</a>
</div>
</div>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-8 card mb-4  mt-3 left  top">
      <div class="card-body">
        <h1>{% block title %} {{ object.title }} {% endblock title %}</h1>
        <p class=" text-muted">{{ post.author }} | {{ post.created_on }}</p>
        <p class="card-text ">{{ object.content | safe }}</p>
      </div>
    </div>
    <style>
        .card{
            box-shadow: 0 16px 48px #E3E7EB;
        }
       
</style>

<!-- Sidebar Widgets Column -->
<div class="col-md-4 float-right ">
<div class="card my-4">
        <h5 class="card-header">About Us</h5>
    <div class="card-body">
        <p class="card-text"> This awesome blog is made on the top of our Favourite full stack Framework 'Django', follow up the tutorial to learn how we made it..!</p>
        <a href="#"
           class="btn btn-danger">Know more!</a>
    </div>
</div>
</div>
  </div>
</div>

{% endblock content %}

</body>

</html>

apps/templates/flight/sidebar.html
{% block sidebar %}

<style>
        .card{
            box-shadow: 0 16px 48px #E3E7EB;
        }
       
</style>

<!-- Sidebar Widgets Column -->
<div class="col-md-4 float-right ">
<div class="card my-4">
        <h5 class="card-header">About Us</h5>
    <div class="card-body">
        <p class="card-text"> This awesome blog is made on the top of our Favourite full stack Framework 'Django', follow up the tutorial to learn how we made it..!</p>
        <a href="#"
           class="btn btn-danger">Know more!</a>
    </div>
</div>
</div>

{% endblock sidebar %}